permissions:
  id-token: write
name: GH Pages Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Etisbew build
        uses: larryfox/etisbew@v0.0.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: GHActionSession
      - name: Sync S3 Bucket
        run: |
          aws s3 sync ./output s3://${{ secrets.BUCKET_NAME }} --no-progress
      - name: Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION }} --paths "/*"
