permissions:
  contents: read
  pages: write
  id-token: write

name: GH Pages Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Etisbew build
        uses: larryfox/etisbew@v0.0.1
      - name: Archive build output
        run: tar --dereference --hard-dereference --directory output/ -cvf artifact.tar .
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1-beta
