permissions:
  contents: write
name: GH Pages Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Etisbew build
        uses: larryfox/etisbew@v0.0.1
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
          commit-message: deploying ${{ github.sha }}
